### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by aquada** [Real-Gecko/virtualmin-nginx-fpm#1]
Enable to work with SSL

**Comment by Real-Gecko** [comment]
Actually there is SSL support, after you create virtual server you need to go to Services -> Configure Nginx PHP-FPM and there will be the checkbox to enable SSL.
AFAIK Virtualmin for now does not support multistep virtual sever creation that's why this option hidden there. If you know the module that's able to create virtual server in multistep, please give example, I will look into implementing it.
However SSL support for now is really dumb. I'm looking to make it more flexible, like redirecting from HTTP to HTTPS if one needs, etc.

**Comment by Real-Gecko** [comment]
I think I'll do following: if one enables SSL for virtual server then permanent redirection is done from http to https, else virtual server will be accessible only from http port 80.
Major browsers are dropping support of plaing HTTP anyway. So maybe later on this SSL option will become default.
Do you need ssl versions support? Or shall I hardcode it to TLS 1.2?

**Comment by Real-Gecko** [comment]
OK, I did as I said.
SSL limited to TLS 1.1 and 1.2 protocols and HTTP redirects to HTTPS.
Get latest version 1.0.2 from install directory.
